name: Build Conda Environment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    name: Conda Stuff
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Give permissions
        run: chmod +x queueserver_emu.sh
      - name: Build Conda Env
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          
          bash -uem ./queueserver_emu.sh --install-{conda,mongo,redis} --default-config