name: Build Conda Environment v2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        repositories: ["NSLS-II-CSX/profile_collection", "NSLS-II-SRX/profile_collection"]

    name: Run all repos
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print out owner and repo
        env:
          GIT_OWNER_REPO: ${{ matrix.repositories }}
        run: |
          IN= "$GIT_OWNER_REPO"
          link_info=$(echo $IN | tr "/" "\n")
          OWNER= "${link_info[0]}""
          REPO= "${link_info[1]}""
          echo "$OWNER"
          echo "$REPO"
