name: Build Conda Environment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        repositories: ["NSLS-II-CSX/profile_collection", "NSLS-II-SRX/profile_collection"]

    name: Run all repos
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print out name and repo
        run: |
          echo "${{ matrix.repositories }}"
