name: Build Conda Environment v2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        repos: [{org: "NSLS-II-CSX", repo: "profile_collection"}, {org: "NSLS-II-SRX", repo: "profile_collection"}]

    name: Run all repos
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print out owner and repo
        run: |
          echo "Organization: ${{matrix.repos.org}}"
          echo "Repository: ${{matrix.repos.repo}}"
