name: Build Conda Environment v2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        repos: [{org: "NSLS-II-CSX", repo: "profile_collection", branch: "main"}, {org: "NSLS-II-SRX", repo: "profile_collection", branch: "main"}]

    name: Run all repos
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print out owner and repo
        run: |
          echo ${{matrix.repos.branch}}
          echo ${{matrix.repos.org}}
          echo ${{matrix.repos.repo}}
      - name: Cloning remote repos
        run: git clone --branch ${{matrix.repos.branch}} "https://github.com/${{matrix.repos.org}}/${{matrix.repos.repo}}"
      - name: Validate
        run: echo "WORKS"