on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test-ipython:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'Ipython_test'
        sparse-checkout-cone-mode: false
    - name: Set up IPython
      run: pip install ipython
    - name: Check for ipython
      run: |
        ipython --version
        ls
        pwd
    - name: Creating ipython profile
      run: ipython profile create test
