on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  test-ipython:
    runs-on: ubuntu-latest
    env:
      PROFILE_NAME: test
      CHECKOUT_FOLDER: Ipython_test
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: ${{env.CHECKOUT_FOLDER}}
        sparse-checkout-cone-mode: false
    - name: Set up IPython
      run: pip install ipython
    - name: Check for ipython
      run: |
        ipython --version
        ls
        pwd
    - name: Creating ipython profile
      run: ipython profile create ${{env.PROFILE_NAME}}
    - name: Go to startup file and add files in checkout folder
      run: |
        cp ${{env.CHECKOUT_FOLDER}}/** $(ipython locate profile ${{env.PROFILE_NAME}})/startup/
    - name: confirm file moved
      run: |
        cd ${{env.CHECKOUT_FOLDER}}
        ls
        echo "Done with Checkout folder"
        cd "$(ipython locate profile ${{env.PROFILE_NAME}})/startup"
        ls
        echo "Done with startup folder"
    - name: run ipython
      run: ipython --profile ${{env.PROFILE_NAME}}