on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test-ipython:
    runs-on: ubuntu-latest
    steps:
    - name: Set up IPython
      run: pip install ipython
    - name: Check for ipython
      run: ipython --version