name: Test Conda Env

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:
  zenodo_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Conda
        uses: conda-incubator/setup-miniconda@v3
      - name: Downloading Conda env
        env:
          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
        run: |
          echo "Downloading conda env..." &&
          wget --progress=dot:giga  "https://zenodo.org/record/10148425/files/${CONDA_ENV_NAME}.tar.gz?download=1" -O "${CONDA_ENV_NAME}.tar.gz"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda_artifact
          path: "2023-3.3-py310-tiled.tar.gz"
  testing_conda_artifact:
    needs: zenodo_artifact
    env:
      CONDA_ENV_NAME: 2023-3.3-py310-tiled
      CONDA_PREFIX: miniconda
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        repos: [{org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "CSX"},
                {org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "SRX"}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Downloading Conda Artifact
        uses: actions/download-artifact@v4
        with:
          name: conda_artifact
      - name: Checking for conda
        run: |
          conda --version
          conda env list
      - name: Extracting conda env
        run: |
          sudo mkdir -v -p "${{ env.CONDA_PREFIX }}/env/${{ env.CONDA_ENV_NAME}}"
          sudo tar -xf "${{ env.CONDA_ENV_NAME}}.tar.gz" -C "${{ env.CONDA_PREFIX }}/env/${{ env.CONDA_ENV_NAME}}"
          echo "DONE"
      - name: starting conda
        run: |
          set +u
          eval "$(conda shell.bash hook)"
          conda activate "${{ env.CONDA_PREFIX }}/env/${{ env.CONDA_ENV_NAME}}"
          conda unpack && echo "Unpacked successfully!"
          set -u
          ls
          conda env list

#      - name: Activating Conda
#        env:
#          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
#        run: |
#          conda activate "$CONDA_ENV_NAME"
#          conda env list
# /home/runner/work/BeamlineCICD/BeamlineCICD/miniconda
#echo "Extracting conda env..."
#sudo mkdir -v -p "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#sudo tar -xf "${CONDA_ENV_NAME}.tar.gz" -C "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#set +u
#
#echo "initialized conda"
#conda init bash
#conda activate "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#sudo conda unpack && echo "Unpacked successfully!"
#set -u
#ls
#conda env list

