name: Test Conda Env

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:
  zenodo_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Conda
        uses: conda-incubator/setup-miniconda@v3
      - name: Downloading Conda env
        env:
          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
        run: |
          echo "Downloading conda env..." &&
          wget --progress=dot:giga  "https://zenodo.org/record/10148425/files/${CONDA_ENV_NAME}.tar.gz?download=1" -O "${CONDA_ENV_NAME}.tar.gz"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda_artifact
          path: "2023-3.3-py310-tiled.tar.gz"
  testing_conda_artifact:
    needs: zenodo_artifact
    env:
      CONDA_ENV_NAME: 2023-3.3-py310-tiled
      CONDA_PREFIX: miniconda
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        repos: [{org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "CSX"},
                {org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "SRX"}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cloning Remote Repos
        run: |
          mkdir "${{matrix.repos.beamline_acronym}}_${{matrix.repos.repo}}"
          git clone -b ${{matrix.repos.branch}} "https://github.com/${{matrix.repos.org}}/${{matrix.repos.repo}}" "${{matrix.repos.beamline_acronym}}_${{matrix.repos.repo}}"
      - name: Configuring defaults
        run: |
          echo "pyOlog config:"
          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/pyOlog.conf -O $HOME/.pyOlog.conf
          cat $HOME/.pyOlog.conf

          echo "Classic databroker v0/v1 config:"
          databroker_conf_dir="$HOME/.config/databroker"
          beamline_acronym="${BEAMLINE_ACRONYM,,}"
          databroker_bl_conf="${beamline_acronym}.yml"
          mkdir -v -p ${databroker_conf_dir}
          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/databroker.yml -O ${databroker_conf_dir}/_legacy_config.yml
          cp -v ${databroker_conf_dir}/_legacy_config.yml ${databroker_conf_dir}/${databroker_bl_conf}
          cat ${databroker_conf_dir}/_legacy_config.yml
          cat ${databroker_conf_dir}/${databroker_bl_conf}

          echo "Tiled profile config:"
          tiled_profiles_dir="$HOME/.config/tiled/profiles/"
          mkdir -v -p "${tiled_profiles_dir}"
          sed 's/^  //' << EOF > "${tiled_profiles_dir}/profiles.yml"
          ${beamline_acronym:-local}:
            direct:
              authentication:
                allow_anonymous_access: true
              trees:
              - tree: databroker.mongo_normalized:Tree.from_uri
                path: /
                args:
                  uri: mongodb://localhost:27017/metadatastore-local
                  asset_registry_uri: mongodb://localhost:27017/asset-registry-local
          EOF
            cat ${tiled_profiles_dir}/profiles.yml

            echo "Kafka config:"
            sed 's/^  //' << EOF > kafka.yml
            ---
              abort_run_on_kafka_exception: false
              bootstrap_servers:
                - localhost:9092
              runengine_producer_config:
                security.protocol: PLAINTEXT
          EOF

            echo "SUDO: Placing kafka config in /etc/bluesky"
            sudo mkdir -v -p /etc/bluesky/
            sudo mv -v kafka.yml /etc/bluesky/kafka.yml
            cat /etc/bluesky/kafka.yml
      - name: Setup Ipython test profile
        env:
          PROFILE_REPO: "https://github.com/${{matrix.repos.org}}/${{matrix.repos.repo}}.git"
          PROFILE_BRANCH: "${{matrix.repos.profile_branch}}"
          TEST_PROFILE: "test"
        run: |
          echo "Preparing test profile"
          rm -rfv profile_collection
            git clone "$PROFILE_REPO" profile_collection
            (
              cd profile_collection
              git checkout "$PROFILE_BRANCH"
              rm -rfv ~/.ipython/profile_${TEST_PROFILE}/
              mkdir -pv ~/.ipython/profile_${TEST_PROFILE}/
              cp -rv startup ~/.ipython/profile_${TEST_PROFILE}/
            )
          echo "COMPLETED STARTING UP"
      - name: Downloading Conda Artifact
        uses: actions/download-artifact@v4
        with:
          name: conda_artifact
      - name: Checking for conda
        run: |
          conda --version
          conda env list
      - name: Extracting conda env
        run: |
          sudo mkdir -v -p "${{ env.CONDA_PREFIX }}/envs/${{ env.CONDA_ENV_NAME}}"
          sudo tar -xf "${{ env.CONDA_ENV_NAME}}.tar.gz" -C "${{ env.CONDA_PREFIX }}/envs/${{ env.CONDA_ENV_NAME}}"
          conda env list
#      - name: starting conda
#        run: |
#          set +u
#          eval "$(conda shell.bash hook)"
#          ls "${{ env.CONDA_PREFIX }}/env"
#          conda activate "/home/runner/work/BeamlineCICD/BeamlineCICD/${{ env.CONDA_PREFIX }}/env/${{ env.CONDA_ENV_NAME}}"
#          sudo conda unpack && echo "Unpacked successfully!"
#          set -u
#          ls
#          conda env list

#conda init bash
#eval "$(conda shell.bash hook)"
#      - name: Activating Conda
#        env:
#          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
#        run: |
#          conda activate "$CONDA_ENV_NAME"
#          conda env list
# /home/runner/work/BeamlineCICD/BeamlineCICD/miniconda
#echo "Extracting conda env..."
#sudo mkdir -v -p "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#sudo tar -xf "${CONDA_ENV_NAME}.tar.gz" -C "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#set +u
#
#echo "initialized conda"
#conda init bash
#conda activate "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#sudo conda unpack && echo "Unpacked successfully!"
#set -u
#ls
#conda env list

