name: Test Conda Env

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:

  zenodo_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading miniconda3
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: False
      - name: Find miniconda.sh
        run: |
          # List home directory to find the miniconda.sh script
          echo "Listing home directory contents:"
          ls -al ~
          
          # Search for the miniconda.sh script in common directories with sudo and redirect output
          echo "Searching for miniconda.sh in the home directory:"
          sudo find ~ -name "miniconda.sh" -print > ~/find_results_home.txt
  
          echo "Searching for miniconda.sh in the /tmp directory:"
          sudo find /tmp -name "miniconda.sh" -print > ~/find_results_tmp.txt
          
          echo "Searching for miniconda.sh in the /usr directory:"
          sudo find /usr -name "miniconda.sh" -print > ~/find_results_usr.txt
  
          # Display the contents of the find results
          echo "Find results in home directory:"
          cat ~/find_results_home.txt
  
          echo "Find results in /tmp directory:"
          cat ~/find_results_tmp.txt
          
          echo "Find results in /usr directory:"
          cat ~/find_results_usr.txt
