name: Test Conda Env

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:

  zenodo_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading miniconda3
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: False
      - name: displaying info
        run: |
          cd /
          ls
          echo "IN runner DIRECTORY"
          cd home/runner
          ls
          
          pwd
          if [ -e directory/miniconda.sh ]; then
            echo "miniconda file exists"
          fi

