name: Test Conda Env

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
      branches: [ "main" ]

jobs:
  zenodo_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Conda
        uses: conda-incubator/setup-miniconda@v3
      - name: Downloading Conda env
        env:
          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
        run: |
          echo "Downloading conda env..." &&
          wget --progress=dot:giga  "https://zenodo.org/record/10148425/files/${CONDA_ENV_NAME}.tar.gz?download=1" -O "${CONDA_ENV_NAME}.tar.gz"
      - name: Upload artifact
        env:
          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
        uses: actions/upload-artifact@v4
        with:
          name: "$CONDA_ENV_NAME"
          path: "$CONDA_ENV_NAME".tar.gz

# /home/runner/work/BeamlineCICD/BeamlineCICD/miniconda
#echo "Extracting conda env..."
#sudo mkdir -v -p "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#sudo tar -xf "${CONDA_ENV_NAME}.tar.gz" -C "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#set +u
#
#echo "initialized conda"
#conda init bash
#conda activate "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
#sudo conda unpack && echo "Unpacked successfully!"
#set -u
#ls
#conda env list

#  testing_conda_artifact:
#    needs: zenodo_artifact
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ ubuntu-latest ]
#        repos: [{org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "CSX"},
#                {org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "SRX"}]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Downloading Conda Artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: 2023-3.3py310-tiled
#      - name: Checking for Conda Env
#        run: conda env list
#      - name: Activating Conda
#        env:
#          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
#        run: |
#          conda activate "$CONDA_ENV_NAME"
#          conda env list